version: '3'
services:
  service:
    build: app
    expose:
      - "8000"
    depends_on:
      - theatre-db
    env_file:
      - ./.env
    volumes:
      - static:/opt/app/static

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static:/data/static
    depends_on:
      - service
    ports:
      - "80:80"

  theatre-db:
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - ./database_dump.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  static:
